#!/bin/bash

cd ..

printf "\n\n#####  Cloning Projects..."

git clone git@github.com:BrenoBeierstedt/o-amarelinho-teste-web.git

git clone git@github.com:BrenoBeierstedt/o-amarelinho-teste-api.git

printf "\n\n##### Copying composer..."
cp o-amarelinho-teste-inicial/docker-compose.yml docker-compose.yml


printf "\n\nAll done! Have a nice day!\n"